uber/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from uber.forms import uberUserLoginForm, uberEmployeeForm, uberCustomerForm
from uber.models import CustomerSchema, db, uberUser, uberEmployee, uberCustomer
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required 

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

#SIGNUP
@auth.route('/signup', methods = ['GET', 'POST'])
#GET: checking to see if data exists
def signup(): 
    form = uberUserLoginForm()
    try: 
        if request.method == 'POST' and form.validate_on_submit(): 
            full_name = form.full_name.data
            user_name = form.user_name.data
            email = form.email.data
            password = form.password.data
            user = uberUser(full_name, user_name, email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'Congrats {full_name}, you have successfully created an account!')

            return redirect(url_for('auth.login'))
    except: 
        raise Exception('Invalid Entry. Please Try Again.')
    return render_template('signup.html', form = form) 

#LOGIN
@auth.route('/login', methods = ['GET', 'POST'])
#GET: checking to match up data in database 
def login(): 
    form = uberUserLoginForm()

    try: 
        if request.method == 'POST' and form.validate_on_submit(): 
            full_name = form.full_name.data
            user_name = form.user_name.data
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = uberUser.query.filter(uberUser.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password): 
                login_user(logged_user)
                flash('Successful Email/Password Login!')
                return redirect(url_for('site.profile'))
            else: 
                flash('Invalid Email/Password', 'auth-failed')
                return redirect(url_for('auth.login'))
    except: 
        raise Exception('Invalid Entry. Please Try Again.')

    return render_template('login.html', form = form)

#LOGOUT 
@auth.route('/logout')
@login_required

def logout():
    logout_user()
    return redirect(url_for('site.home'))



#EMPLOYEE APPLICATION
@auth.route('/apply', methods = ['POST', 'GET'])

def apply():
    form = uberEmployeeForm()
    try: 
        if request.method == 'POST' and form.validate_on_submit():
            full_name = form.full_name.data
            print(full_name)
            user_name = form.user_name.data
            print(user_name)
            email = form.email.data
            print(email)
            phone_num = form.phone_num.data
            print(phone_num)
            address = form.address.data
            print(address)
            birthday = form.birthday.data
            print(birthday)
            ref_name = form.ref_name.data
            print(ref_name)
            ref_phone = form.ref_phone.data
            print(ref_phone)
            ref_email = form.ref_email.data
            print(ref_email)
            today_date = form.today_date.data
            print(today_date)
            employee = uberEmployee(full_name, user_name, email, phone_num, address, birthday, ref_name, ref_phone, ref_email, today_date)

            db.session.add(employee)
            db.session.commit()

            flash(f'Congrats {full_name}, you have successfully submitted an application!')

            return redirect(url_for('site.thank_you'))
    except: 
        raise Exception('Invalid Entry. Please Try Again.')
    return render_template('apply.html', form = form) 

#CUSTOMER REQUEST 

@auth.route('/cust_request', methods = ['POST', 'GET'])

def cust_request():
    form = uberCustomerForm()
    try: 
        if request.method == 'POST' and form.validate_on_submit(): 
            full_name = form.full_name.data
            print(full_name)
            email = form.email.data
            print(email)
            phone_num = form.phone_num.data
            print(phone_num)
            num_beds = form.num_beds.data
            print(num_beds)
            num_bath = form.num_bath.data
            print(num_bath)
            sqft = form.sqft.data
            print(sqft)
            req_date = form.req_date.data
            print(req_date)
            req_time = form.req_time.data
            print(req_time)
            customer = uberCustomer(full_name, email, phone_num, num_beds, num_bath, sqft, req_date, req_time)

            db.session.add(customer)
            db.session.commit()

            flash(f'Congrats {full_name}, you have successfully submitted an application!')

            return redirect(url_for('site.thank_you'))
    except: 
        raise Exception('Invalid Entry. Please Try Again.')
    return render_template('request.html', form = form) 

uber/site/routes.py
from flask import Blueprint, render_template
#from flask_login import login_required
from ..models import uberUser


site = Blueprint('site', __name__, template_folder = 'site_templates')


@site.route('/')
def home():
    return render_template('index.html')

@site.route('/about_us')
def about_us():
    return render_template('about_us.html')

@site.route('/how_it_works')
def how_it_works():
    return render_template('how_it_works.html')

@site.route('/profile')
#@login_required
def profile():
    return render_template('profile.html')

@site.route('/thank_you')
def thank_you():
    return render_template('thank_you.html')

uber/templates/application.html
<!--EMPLOYEE FORM-->
<form method = "POST">
    {{ form.hidden_tag() }} 
    <div class = "become-cleaner-form">
        <fieldset id="full-name-cleaner-entry">
        </br>
            {{ form.full_name(class = "form-control", placeholder = "Full Name")}}
        </fieldset>
        <fieldset id = "user-name-entry">
        </br>
            {{ form.user_name(class = "form-control", placeholder = "Enter User Name")}}
        </fieldset>
        <fieldset id = "email-cleaner-entry">
        </br>
            {{ form.email(class = "form-control", placeholder = "Enter Email")}}
        </fieldset>
        <fieldset id="phone-num-cleaner-entry">
        </br> 
            {{ form.phone_num(class = "form-control", placeholder = "Enter Phone Number")}}
        </fieldset>
        <fieldset id="address-cleaner-entry">
        </br>
            {{ form.address(class = "form-control", placeholder = "Enter Address")}}
        </fieldset>
        <fieldset id="birthday-cleaner-entry">
        </br>
            {{ form.birthday(class = "form-control", placeholder = "Enter Birthday (00/00/0000)")}}
        </fieldset>
        <fieldset id="ref-name-entry">
        </br>
            {{ form.ref_name(class = "form-control", placeholder = "Enter Reference Name(s)")}}
        </fieldset>
        <fieldset id="ref-phone-cleaner-entry">
        </br>
            {{ form.ref_phone(class = "form-control", placeholder = "Enter Reference Phone Number(s)")}}
        </fieldset>
        <fieldset id="ref-email-cleaner-entry">
        </br>
            {{ form.ref_email(class = "form-control", placeholder = "Enter Reference Email(s)")}}
        </fieldset>
        <fieldset id="today-date-cleaner-entry">
        </br>
            {{ form.today_date(class = "form-control", placeholder = "Enter Today Date")}}
        </fieldset>
        {{ form.submit_button(class = "btn btn-secondary btn-block")}}
    </div>
</form>

uber/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Uber Clean</title>
</head>
<body>
    <nav class = "nav">
        <!--Top Left Corner Logo/ Clickable for "Home"-->
        <div>
            <img src = "../static/images/white.png" alt = "Uber Clean Logo" id = "nav_logo_image">
                <ul id = "nav_buttons">
                    <a href="{{ url_for('site.home') }}">
                        <li>Home</li>
                    </a>
                    <a href="{{ url_for('site.about_us') }}">
                        <li>About Us</li>
                    </a>
                    <a href="{{ url_for('site.how_it_works') }}">
                        <li>How It Works</li>
                    </a>
                    <a href="{{ url_for('auth.login') }}">
                        <li>Login</li>
                    </a>
                    <a class = "btn btn-secondary btn-block" href="{{ url_for('auth.signup') }}">
                        <li  id = 'last-btn'>Sign Up</li>
                    </a> 
                </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

uber/templates/forms.html
<!-- LOGIN / SIGN UP ENTRY FORM-->
<form method = "POST">
    {{ form.hidden_tag() }} 
    <div class = "entry-form">
        <fieldset id="full-name-entry">
        </br>
            {{ form.full_name(class = "form-control", placeholder = "Full Name")}}
        </fieldset>
        </br>
        <fieldset id="user-name-entry">
        </br>
            {{ form.user_name(class = "form-control", placeholder = "Username")}}
        </fieldset>
        </br>
        <fieldset id = "email-entry">
        </br>
            {{ form.email(class = "form-control", placeholder = "Enter Email")}}
        </fieldset>
        </br>
        <fieldset id="password-entry">
        </br>
            {{ form.password(class = "form-control", placeholder = "Enter Password")}}
        </br>
        </fieldset>
        {{ form.submit_button(class = "btn btn-secondary btn-block")}}
    </div>
</form>

uber/templates/request-temp.html
<!--BOOK A CLEAN FORM-->
<form method = "POST">
    {{ form.hidden_tag() }} 
    <div class = "book-clean-form">
        <fieldset id = "full-name-entry">
        </br>
            {{ form.full_name(class = "form-control", placeholder = "Your Full Name")}}
        </fieldset>
        <fieldset id="email-entry">
        </br>
            {{ form.email(class = "form-control", placeholder = "Email Address")}}
        </fieldset>
        <fieldset id="phone-entry">
        </br>
            {{ form.phone_num(class = "form-control", placeholder = "Phone Number")}}
        </fieldset>
        <fieldset id="beds-entry">
        </br>
            {{ form.num_beds(class = "form-control", placeholder = "Number of Bedrooms")}}
        </fieldset>
        <fieldset id="baths-entry">
        </br>
            {{ form.num_bath(class = "form-control", placeholder = "Number of Bathrooms")}}
        </fieldset>
        <fieldset id="sqft-entry">
        </br>
            {{ form.sqft(class = "form-control", placeholder = "Estimated Square Footage of Residence")}}
        </fieldset>
        <fieldset id="date-entry">
        </br>
            {{ form.req_date(class = "form-control", placeholder = "Date Requested For Cleaning")}}
        </fieldset>
        <fieldset id="time-entry">
        </br>
            {{ form.req_time(class = "form-control", placeholder = "Time Requested For Cleaning")}}
        </fieldset>
        {{ form.submit_button(class = "btn btn-secondary btn-block")}}
    </div>
</form>